name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: ci - macos
    runs-on: macos-latest
    env:
      GOFLAGS: -mod=vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: Test code
        run: go test ./...
      - name: Vet
        run: go vet ./...
  build:
    runs-on: macos-latest
    env:
      GOFLAGS: -mod=vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: Build darwin/arm64 binary
        run: |
          GOOS=darwin GOARCH=arm64 go build -o lazyapple .
  check-codebase:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: Check Cheatsheet
        run: |
          go run scripts/cheatsheet/main.go check
      - name: Check Vendor Directory
        # ensure our vendor directory matches up with our go modules
        run: |
          go mod vendor && git diff --exit-code || (echo "Unexpected change to vendor directory. Run 'go mod vendor' locally and commit the changes" && exit 1)
  lint:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Format code
        run: |
          if [ $(find . ! -path "./vendor/*" -name "*.go" -exec gofmt -s -d {} \;|wc -l) -gt 0 ]; then
           find . ! -path "./vendor/*" -name "*.go" -exec gofmt -s -d {} \;
           exit 1
          fi
      - name: errors
        run: golangci-lint run
        if: ${{ failure() }}
